version: '3.8'

services:

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=5
      - KEEP_HISTORY=10
    volumes:
      - .allure/allure-results:/app/allure-results
      - .allure/allure-reports:/app/default-reports
    networks:
      - allure-network

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure-ui
    ports:
      - "5252:5252"
    environment:
      - ALLURE_DOCKER_PUBLIC_API_URL=http://localhost:5050
      - ALLURE_DOCKER_PUBLIC_UI_URL=http://localhost:5252
    depends_on:
      - allure
    networks:
      - allure-network

networks:
  allure-network:
    driver: bridge